export const HOME_ROUTE_PATH = '/'
export const SAMPLE_ROUTE_PATH = '/sample'
export const TODOS_ROUTE_PATH = '/todos'
export const VIDEO_ANIMATION = '/videoAnimation'
export const DRAG_DROP = '/dragDrop'
